### ISSUE TITLE
No matching federated identity record found for presented assertion

### ISSUE THREAD

**Issue by pavelm10** [Azure/azure-workload-identity#977]
**Describe the bug**
We have migrated from pod-identities to workload-identities in Azure AKS. Randomly/sometimes we get this error:
`azure.core.exceptions.ClientAuthenticationError: Azure Active Directory error '(unauthorized_client):"AADSTS70021: No matching federated identity record found for presented assertion. Assertion Issuer: 'https://westeurope.oic.prod-aks.azure.com/<TENANT_ID>/<SOME_ID>/'. Assertion Subject: 'system:serviceaccount:<namespace>:<service-account-name>'. Assertion Audience: 'api://AzureADTokenExchange'. https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation`

We are using user assigned managed identity as principal for pods to access azure resources. Federated credential exists for the given managed identity. `Cluster Issuer URL` shown for the federated credential is the same as in the error log. Service account with the same name as is in the log exists as well. The pods were working fine, but after few hours this error occurred which kept the pod restarting. 

I found https://azure.github.io/azure-workload-identity/docs/troubleshooting.html#aadsts70021-no-matching-federated-identity-record-found-for-presented-assertion
But the backslash is not missing, as is obvious from the logs. Also the OIDC is enabled:
```
az aks show \
  --name $AKS_NAME \
  --resource-group $AKS_RESOURCE_GROUP \
  --query oidcIssuerProfile.enabled \
  --output tsv \
  --only-show-errors
```
Returns "true".
Also the OIDC endpoints are accessible:
```
curl ${SERVICE_ACCOUNT_ISSUER}/.well-known/openid-configuration
curl ${SERVICE_ACCOUNT_ISSUER}/openid/v1/jwks
```

I deleted federated credential and the service account and did the setup of federated credential and service account again. This did not help with the restarts, so then I restarted the deployment completely and no more restarts were happening since then.

**Steps To Reproduce**
1. Enable workload identities on the cluster
2. Create user assigned managed identity resource
3. Give the identity access to some Azure resources, e.g. data table
4. Create service account  with client ID set to the one of the managed identity
5. Create federated credential:
```
az identity federated-credential create \
  --name "${FEDERATED_CREDENTIAL_NAME}" \
  --identity-name "${UAMI}" \
  --resource-group "${SVC_RESOURCE_GROUP}" \
  --issuer "${AKS_OIDC_ISSUER}" \
  --subject system:serviceaccount:"${K8S_SERVICE_NAMESPACE}":"${SERVICE_ACCOUNT_NAME}"
```
6. Run a deployment which authenticates via workload-identities using the service account
7. After some time (or never - hard to say when this occurs) the error aforementioned will occur.

**Expected behavior**

When the workload-identities are setup correctly, the pods do not loss access to the azure resources due to losing credential.

**Logs**
```
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/storage/blob/_download.py", line 411, in _initial_request
    location_mode, response = self._clients.blob.download(
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/storage/blob/_generated/operations/_blob_operations.py", line 1700, in download
    pipeline_response = self._client._pipeline.run(  # type: ignore # pylint: disable=protected-access
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 205, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/core/pipeline/policies/_redirect.py", line 160, in send
    response = self.next.send(request)
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/storage/blob/_shared/policies.py", line 543, in send
    raise err
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/storage/blob/_shared/policies.py", line 517, in send
    response = self.next.send(request)
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 69, in send
    response = self.next.send(request)
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/core/pipeline/policies/_authentication.py", line 115, in send
    self.on_request(request)
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/core/pipeline/policies/_authentication.py", line 92, in on_request
    self._token = self._credential.get_token(*self._scopes)
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/identity/_internal/decorators.py", line 32, in wrapper
    token = fn(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/identity/_credentials/managed_identity.py", line 115, in get_token
    return self._credential.get_token(*scopes, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/identity/_internal/get_token_mixin.py", line 70, in get_token
    token = self._request_token(*scopes, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/identity/_credentials/client_assertion.py", line 59, in _request_token
    token = self._client.obtain_token_by_jwt_assertion(scopes, assertion, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/identity/_internal/aad_client.py", line 65, in obtain_token_by_jwt_assertion
    return self._run_pipeline(request, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/identity/_internal/aad_client.py", line 97, in _run_pipeline
    return self._process_response(response, now)
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/identity/_internal/aad_client_base.py", line 132, in _process_response
    _raise_for_error(response, content)
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/identity/_internal/aad_client_base.py", line 306, in _raise_for_error
    raise ClientAuthenticationError(message=message, response=response.http_response)
azure.core.exceptions.ClientAuthenticationError: Azure Active Directory error '(unauthorized_client) AADSTS70021: No matching federated identity record found for presented assertion. Assertion Issuer: 'https://westeurope.oic.prod-aks.azure.com/<TENANT_ID>/<SOME_ID>/'. Assertion Subject: ' system:serviceaccount:<namespace>:<service-account-name>'. Assertion Audience: 'api://AzureADTokenExchange'. https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation

Content: {"error":"unauthorized_client","error_description":"AADSTS70021: No matching federated identity record found for presented assertion. Assertion Issuer: 'https://westeurope.oic.prod-aks.azure.com/<TENANT_ID>/<SOME_ID>/'. Assertion Subject: ' system:serviceaccount:<namespace>:<service-account-name>'. Assertion Audience: 'api://AzureADTokenExchange'. https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation\r\n"error_codes":[70021]}
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/app/src/app.py", line 410, in main
    job = Job(
  File "/app/src/app.py", line 127, in __init__
    blob = service.download(blob_name)
  File "/app/src/models.py", line 19, in download
    self._blob_service.get_blob_client(
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/storage/blob/_blob_client.py", line 871, in download_blob
    return StorageStreamDownloader(**options)
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/storage/blob/_download.py", line 359, in __init__
    self._response = self._initial_request()
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/storage/blob/_download.py", line 457, in _initial_request
    process_storage_error(error)
  File "/root/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.9/lib/python3.9/site-packages/azure/storage/blob/_shared/response_handlers.py", line 120, in process_storage_error
    error_code = error_dict.get('code')
AttributeError: 'str' object has no attribute 'get'
```

**Environment**

- Kubernetes version (use `kubectl version`): 1.25.5
- Cloud provider or hardware configuration: Azure, nodes: Standard_D4ds_v4
- OS (e.g: `cat /etc/os-release`): linux AMD64, Ubuntu 22.04.2 LTS
- Kernel (e.g. `uname -a`): 5.15.0-1038-azure
- Install tools:
- Network plugin and version (if this is a network-related bug): Azure CNI
- Others: 
  - Container runtime: containerd://1.7.1+azure-1
  - Application runtime: Python 3.9.14

**Comment by Eneuman** [comment]
@pavelm10 We are also seeing this issue, did you ever find a solution for this?

**Comment by pavelm10** [comment]
@Eneuman The fix is described in this ticket description. I am now in contact with Azure AAD team, but currently there is no explanation or further insights.

**Comment by epiekarski** [comment]
@pavelm10  Any new updates on this? I am receiving the same issue on my end with my deployment.

**Comment by pavelm10** [comment]
@epiekarski no progress. Azure support asked me for correlation ID of the error when it emerged, but originally I did not noted it down. Now I am not able to replicate the issue so they cannot help me with my request at the moment. I would suggest you to create support request at Azure and provide the correlation ID. 

Extra note: I was able to artificially make the exact error appear by deleting federated credential at the given user assigned managed identity. When we first got the error I checked the federation is there, so it is weird that removal led to the same error. However, this artificial replication of the issue was no help for them even though I provided the correlation ID.
